import type { Metadata } from 'next'
import { Inter, Poppins } from 'next/font/google'
import './globals.css'
import Header from '@/components/layout/Header'

const inter = Inter({ subsets: ['latin'] })
const poppins = Poppins({ subsets: ["latin"], weight: ["400","500","600","700","800","900"] })

export const metadata: Metadata = {
  title: 'Enderebil',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${poppins.className} bg-[#EDEEF0]`}>
        <Header />
        <div className='container sm:px-8 px-4'>
          {children}
        </div>
      </body>
    </html>
  )
}
